"""ConversationStorePort: persistence for conversations and their messages."""

from typing import Protocol

from app.domain.models import Conversation, Message


class ConversationStorePort(Protocol):
    async def create_conversation(self, conversation: Conversation) -> None:
        """Insert a conversation. `create`, not `save`: the id is generated by
        the caller, so id generation lives in exactly one place."""
        ...

    async def get_conversation(self, conversation_id: str) -> Conversation | None: ...

    async def list_conversations(self, limit: int) -> list[Conversation]:
        """Most recently active first — the order the sidebar shows."""
        ...

    async def delete_conversation(self, conversation_id: str) -> bool:
        """Delete a conversation and its messages. Returns whether it existed."""
        ...

    async def add_turn(self, messages: list[Message], title: str | None = None) -> None:
        """Persist a completed turn and bump the conversation's activity time.

        The whole turn arrives at once because a turn is only ever written after
        the model has answered — a failed generation persists nothing. Passing
        `title` sets it, which is how the first turn names its conversation.
        """
        ...

    async def rename_conversation(self, conversation_id: str, title: str) -> None:
        """Replace a conversation's title. Used only by the title generator,
        after a turn has already been stored."""
        ...

    async def get_recent_messages(self, conversation_id: str, limit: int) -> list[Message]:
        """The most recent `limit` messages, oldest first — ready to be used as
        prompt context without the caller re-sorting."""
        ...

    async def get_messages(self, conversation_id: str) -> list[Message]:
        """Every message, oldest first."""
        ...
